apiVersion: v2
name: @project.artifactId@
description: A Helm chart for Spring 6 Project
type: application
# Disable Sonar warning for invalid semver: This value is set by Maven filtering
# and will be replaced with a valid version number during the build process.
version: @helm.chart.version@
appVersion: @project.version@

dependencies:
  - name: spring-6-auth-server
    version: "v0.0.4-SNAPSHOT"
    repository: "oci://registry-1.docker.io/domboeckli"
  - name: spring-6-rest-mvc-mysql
    version: v0.0.3-SNAPSHOT
    repository: "oci://registry-1.docker.io/domboeckli"
  - name: spring-6-rest-mvc
    version: "v0.0.3-SNAPSHOT"
    repository: "oci://registry-1.docker.io/domboeckli"
