global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: spring-6-resttemplate

replicaCount: 1

image:
  # Those values are set by Maven filtering
  # and will be replaced with a valid version number during the build process.
  registry: @docker.repo@
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8086
  targetPort: 8086
  nodePort: 30086

externalAccess:
  host: "localhost"
  protocol: "http"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

mysql:
  database: restmvcdb

  port: 3306
  targetPort: 3306
  nodePort: 30306

  user: restadmin
  password: password

  rootPassword: verysecret

  serviceFQDN:

authServer:
  port: 9000
  targetPort: 9000
  nodePort: 30900

  serviceFQDN:

restMvc:
  port: 8081
  targetPort: 8081
  nodePort: 30081

  serviceFQDN:

ingress:
  enabled: false

# Section for overriding values in subcharts defined in the Chart.yaml

spring-6-auth-server:
  spring:
    issuer:
      uri: "http://spring-6-resttemplate-spring-6-auth-server.spring-6-resttemplate.svc.cluster.local:9000"

spring-6-rest-mvc:
  authServer:
    enabled: false
    serviceFQDN: "spring-6-resttemplate-spring-6-auth-server.spring-6-resttemplate.svc.cluster.local"
  mysql:
    enabled: false
    serviceFQDN: "spring-6-resttemplate-spring-6-rest-mvc-mysql.spring-6-resttemplate.svc.cluster.local"
  spring:
    oauth2ResourceServer:
      issuerUri: "http://spring-6-resttemplate-spring-6-auth-server.spring-6-resttemplate.svc.cluster.local:9000"