rest:
  template:
    base:
      url: "http://localhost:8080"
    user: "master"
    password: "password"
    
server:
  port: 8081    
  
logging:
  level:
    org.zalando.logbook: TRACE
    
logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000"
      client:
        registration:
          springauth:
            client-id: messaging-client
            client-secret: secret
            scope[0]: message.read
            scope[1]: message.write
            authorization-grant-type: client_credentials
            provider: springauth
        provider:
          springauth:
            authorization-uri: "http://localhost:9000/auth2/authorize"
            token-uri: "http://localhost:9000/oauth2/token"
            
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always              
