---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.4.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: verysecret
            - name: MYSQL_DATABASE
              value: restmvcdb
            - name: MYSQL_USER
              value: restadmin
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-storage
          emptyDir: { }
        - name: mysql-init-script
          configMap:
            name: mysql-init-script
