### this retrieves the bearer token. use the token in the request below
POST http://localhost:9000/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=user&client_secret=password&scope=message.read message.write
