###
GET http://localhost:{{rest-mvc-port}}/api/v1/beer/listBeers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

###
GET http://localhost:{{rest-mvc-port}}/api/v1/beer/getBeerById/5bdbb1e6-dfc9-4829-8e0a-4edc74ffc07e
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

###
POST http://localhost:{{rest-mvc-port}}/api/v1/beer/createBeer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "version": 0,
  "beerName": "presidente",
  "beerStyle": "LAGER",
  "upc": "xx",
  "quantityOnHand": 5,
  "price": 27.16
}

###
PUT http://localhost:{{rest-mvc-port}}/api/v1/beer/editBeer/4908886e-8df4-4df1-bdb0-6ac0bae289af
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "version": 0,
  "beerName": "altered Beername",
  "beerStyle": "LAGER",
  "upc": "",
  "quantityOnHand": 0,
  "price": 27.16
}

###
PATCH http://localhost:{{rest-mvc-port}}/api/v1/beer/patchBeer/9d07c34b-36fb-4108-b9ca-0de3393ea2ab
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "beerName": "patched Beername"
}

###
DELETE http://localhost:{{rest-mvc-port}}/api/v1/beer/deleteBeer/6ab05faf-743d-443b-8ad6-5e8ae531d12d
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
