###
< scripts/traceparent.js
GET http://localhost:{{rest-mvc-port}}/api/v1/customer/listCustomer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-resttemplate

###
< scripts/traceparent.js
GET http://localhost:{{rest-mvc-port}}/api/v1/customer/getCustomerById/a8a783fd-c4f1-4126-8fca-0e148c43759f
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-resttemplate

###
< scripts/traceparent.js
POST http://localhost:{{rest-mvc-port}}/api/v1/customer/createCustomer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-resttemplate

{
  "customerName": "eder",
  "version": "0"
}

###
< scripts/traceparent.js
PUT http://localhost:{{rest-mvc-port}}/api/v1/customer/editCustomer/4908886e-8df4-4df1-bdb0-6ac0bae289af
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-resttemplate

{
  "customerName": "editedCustomerName",
  "version": "77"
}

###
< scripts/traceparent.js
PUT http://localhost:{{rest-mvc-port}}/api/v1/customer/patchCustomer/4908886e-8df4-4df1-bdb0-6ac0bae289af
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-resttemplate

{
  "customerName": "patchedCustomerName"
}

###
< scripts/traceparent.js
DELETE http://localhost:{{rest-mvc-port}}/api/v1/customer/deleteCustomer/9b6f18b9-f521-4400-8699-7e66ae2261ba
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-resttemplate
