###
GET http://localhost:8080/api/v1/customer/listCustomer
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/api/v1/customer/getCustomerById/6294eedb-ce3d-4153-81cd-99b292f3d263
Accept: application/json
Content-Type: application/json

###
POST http://localhost:8080/api/v1/customer/createCustomer
Accept: application/json
Content-Type: application/json

{
  "customerName": "eder",
  "version": "0"
}

###
PUT http://localhost:8080/api/v1/customer/editCustomer/4908886e-8df4-4df1-bdb0-6ac0bae289af
Accept: application/json
Content-Type: application/json

{
  "customerName": "editedCustomerName",
  "version": "77"
}

###
PUT http://localhost:8080/api/v1/customer/patchCustomer/4908886e-8df4-4df1-bdb0-6ac0bae289af
Accept: application/json
Content-Type: application/json

{
  "customerName": "patchedCustomerName"
}

###
DELETE http://localhost:8080/api/v1/customer/deleteCustomer/9b6f18b9-f521-4400-8699-7e66ae2261ba
Accept: application/json
Content-Type: application/json