###
GET http://localhost:8081/api/v1/customer/listCustomer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

###
GET http://localhost:8081/api/v1/customer/getCustomerById/a8a783fd-c4f1-4126-8fca-0e148c43759f
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

###
POST http://localhost:8081/api/v1/customer/createCustomer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "customerName": "eder",
  "version": "0"
}

###
PUT http://localhost:8081/api/v1/customer/editCustomer/4908886e-8df4-4df1-bdb0-6ac0bae289af
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "customerName": "editedCustomerName",
  "version": "77"
}

###
PUT http://localhost:8081/api/v1/customer/patchCustomer/4908886e-8df4-4df1-bdb0-6ac0bae289af
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "customerName": "patchedCustomerName"
}

###
DELETE http://localhost:8081/api/v1/customer/deleteCustomer/9b6f18b9-f521-4400-8699-7e66ae2261ba
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
