apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-template.fullname" . }}-spring-mysql-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.user | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.password | quote }}